spring.application.name=smart-commerce-ai

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/smartcommerceai
spring.datasource.username=root
spring.datasource.password=#M.S.Dhoni07@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# OPTIONAL (RECOMMENDED)
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect